### ISSUE TITLE
set up basic wireframes

### ISSUE THREAD

**Issue by djbaker** [rainbow-table/volunteer#10]

**Comment by tournetorres** [comment]
![voluntreeWIREF.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594b1c3d69b504001a0550d4/125516c66e82c728ace21e0d46fe9b96368c97bb8aec886a9678d6d665043761260ea62864c7b96aea1b2d590a5d1afa125f0e16f5ad892ba7e568228a5409e5c3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc0e93822e489894a3b1b1755.png)

**Comment by tournetorres** [comment]
![voluntreeWIREF.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594b1c3d69b504001a0550d4/125516c66e82c728ace21e0d46fe9b96368c97bb8aec886a9678d6d665043761260ea62864c7b96aea1b2d590a5d1afa125f0e16f5ad892ba7e568228a5409e5c3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0e93822e183894c371c1755.jpg)
